!  Copyright (C) 2019, respective authors of MCFM.
!
!  This program is free software: you can redistribute it and/or modify it under
!  the terms of the GNU General Public License as published by the Free Software
!  Foundation, either version 3 of the License, or (at your option) any later
!  version.
!
!  This program is distributed in the hope that it will be useful, but WITHOUT ANY
!  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
!  PARTICULAR PURPOSE. See the GNU General Public License for more details.
!
!  You should have received a copy of the GNU General Public License along with
!  this program. If not, see <http://www.gnu.org/licenses/>
 
*********************************************************
*AUTHOR: FABIO MALTONI                                  *
*DATE  : 2/15/2003                                     *
*NOTES : PROGRAM GENERATED BY ToFortran.m               *
*        AMPLITUDES CALCULATED BY ALBERTO FRIZZO        *
*********************************************************

      function  Appppp(I1,I2,I3,I4,I5)
* ---------------------------------------------------------------------
*                            1+ 2+ 3+ 4+ 5+                            
* ---------------------------------------------------------------------


      IMPLICIT NONE
      include 'types.f'
      include 'constants.f'
      include 'nf.f'
      include 'mxpart.f'
      include 'cplx.h'
      complex(dp) Appppp
      include 'sprods_com.f'
      include 'zprods_com.f'
      integer::I1,I2,I3,I4,I5
      real(dp)::MSQ      

      MSQ=
     & +s(i1,i2)+s(i1,i3)+s(i1,i4)+s(i1,i5)
     &          +s(i2,i3)+s(i2,i4)+s(i2,i5)
     &                   +s(i3,i4)+s(i3,i5)
     &                            +s(i4,i5)

      Appppp=MSQ**2/(za(i1,i2)*za(i2,i3)*za(i3,i4)*za(i4,i5)*za(i5,i1))

      END

