!  Copyright (C) 2019, respective authors of MCFM.
!
!  This program is free software: you can redistribute it and/or modify it under
!  the terms of the GNU General Public License as published by the Free Software
!  Foundation, either version 3 of the License, or (at your option) any later
!  version.
!
!  This program is distributed in the hope that it will be useful, but WITHOUT ANY
!  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
!  PARTICULAR PURPOSE. See the GNU General Public License for more details.
!
!  You should have received a copy of the GNU General Public License along with
!  this program. If not, see <http://www.gnu.org/licenses/>
 
      subroutine wt2gen(q,wt2)
      implicit none
      include 'types.f'
      include 'constants.f'
      include 'mxpart.f'
      include 'limits.f'
      include 'breit.f'
      include 'energy.f'
c----given a set of momenta generated calculate the weight 
c----which would have been assigned had it been generated by 
c----routine phase4      
      real(dp):: q(mxpart,4),wt2,s3,ymax,dot
      real(dp):: w3,wt0
      parameter(wt0=one/16._dp/pi)
      s3=two*dot(q,6,7)
      ymax=log(sqrts/sqrt(s3))
      if (n3 == 0) then
         w3=wsqmax-wsqmin
      elseif (n3 == 1) then
        call breitw1(s3,wsqmin,wsqmax,mass3,width3,w3)       
      endif
      wt2=wt0*four*ymax*w3/sqrts**2
c      write(6,*) 'x1*x2=',s3/sqrts**2
c      pause
c      write(6,*) 'ymax',ymax
c      write(6,*) 'w3',w3
c      write(6,*) 'sqrts',sqrts
c      write(6,*) 'wt2',wt2
     
      return
      end






